# Generated by Django 3.1.5 on 2021-01-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=0, upload_to='product_image'),
            preserve_default=False,
        ),
    ]
